baseURL = "http://example.org/"
languageCode = "en-us"
title = "test driven infrastructure"

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme="blood"
custom_css = "css/custom.css"
