---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # start a ubuntu-20.04 instance with systemd enabled
  - name: instance
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: testinfra
#  name: ansible
